In [1]:
import numpy as np

In [2]:
# Creación de un array unidimensional, a partir de una lista.

lista = [2,3,5]

array1 = np.array(lista)
array1

# Output: array([2, 3, 5])

array([2, 3, 5])

In [4]:
# Creación de un array tridimensional, a partir de una lista de listas de listas.
lista3 = [[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]]
array3 = np.array(lista3)
array3


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [5]:
# creamos un array unidimensional con números del 1 al 9

array4 = np.arange(1,10)
array4

# Output: array([1, 2, 3, 4, 5, 6, 7, 8, 9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# creamos un array unidimensional con números del 1 al 9 con saltos de dos en dos

array5 = np.arange(1,10, 2)
array5

# Output: array([1, 3, 5, 7, 9])

array([1, 3, 5, 7, 9])

In [7]:
# Creacion de un arrays unidimensional 

ceros1 = np.zeros(3, dtype = float)
ceros1

# Output: array([0., 0., 0.])

array([0., 0., 0.])

In [8]:
# Creacion de un arrays bidimensional

ceros2 = np.zeros((2,3), dtype = int)
ceros2

# Output: array([[0, 0, 0],[0, 0, 0]])

array([[0, 0, 0],
       [0, 0, 0]])

In [9]:
# # Creacion de un arrays tridimensional. 2 matrices de 3 filas x 5 columnas. 

ceros3 = np.zeros((2,3, 5), dtype = int)
ceros3

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

In [10]:
# unidimensional 

unos1 = np.ones(4)
unos1
# Output: array([1., 1., 1., 1.])

array([1., 1., 1., 1.])

In [11]:
# bidimensional, 2 filas x 3 columnas

unos2 = np.ones((2,3))
unos2
# Output: array([[1., 1., 1.],       [1., 1., 1.]])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
# tridimensional. 2 matrices de 3 filas x 6 columnas

unos3 = np.ones((2,3,6))
unos3

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

In [13]:
np.empty((2,3))

# Output: array([[0.0e+000, 1.5e-323, 2.0e-323], [2.5e-323, 3.0e-323, 4.0e-323]])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
iden2 = np.identity(4)
iden2

''' Output: 
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]]) '''

' Output: \narray([[1., 0., 0., 0.],\n       [0., 1., 0., 0.],\n       [0., 0., 1., 0.],\n       [0., 0., 0., 1.]]) '

In [15]:
eye1 = np.eye(4)
eye1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
# movemos la diagonal una posición hacia arriba

eye2 = np.eye(4, k = 1)
eye2

''' Output: 
array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])'''

' Output: \narray([[0., 1., 0., 0.],\n       [0., 0., 1., 0.],\n       [0., 0., 0., 1.],\n       [0., 0., 0., 0.]])'

In [17]:
# movemos la diagonal dos posiciones hacia arriba

eye3 = np.eye(4, k = 2)
eye3

''' Output: 
array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])   '''

' Output: \narray([[0., 0., 1., 0.],\n       [0., 0., 0., 1.],\n       [0., 0., 0., 0.],\n       [0., 0., 0., 0.]])   '

In [18]:
# lo mismo para valores negativos

eye4 = np.eye(4, k = -1)
eye4

'''# Output: 
array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])       '''

'# Output: \narray([[0., 0., 0., 0.],\n       [1., 0., 0., 0.],\n       [0., 1., 0., 0.],\n       [0., 0., 1., 0.]])       '

In [19]:
lista1 = [2,3,5]

array1 = np.array(lista1)

lista2 = [[2,3,5],[2,3,5]]

array2 = np.array(lista2)

In [20]:
# Para generara dos arrays de 3 filas x  5 columnas con números aleatorios del 0-100
a = np.random.randint(0,100, (2,3,5))
a

'''# Output: 
array([[[ 5, 83, 49, 80, 75],
        [ 3, 46, 38, 13, 77],
        [74, 19, 58, 95, 51]],

       [[60, 60, 14, 98, 86],
        [14, 37,  7, 92, 26],
        [29, 83, 67, 54, 33]]])     '''

'# Output: \narray([[[ 5, 83, 49, 80, 75],\n        [ 3, 46, 38, 13, 77],\n        [74, 19, 58, 95, 51]],\n\n       [[60, 60, 14, 98, 86],\n        [14, 37,  7, 92, 26],\n        [29, 83, 67, 54, 33]]])     '

In [21]:
# Generando dos arrays de 3 filas x  5 columnas con números aleatorios del 0-100
np.random.rand(2,3,4)

'''# Output: 
array([[[ 5, 83, 49, 80, 75],
        [ 3, 46, 38, 13, 77],
        [74, 19, 58, 95, 51]],

       [[60, 60, 14, 98, 86],
        [14, 37,  7, 92, 26],
        [29, 83, 67, 54, 33]]]) '''

'# Output: \narray([[[ 5, 83, 49, 80, 75],\n        [ 3, 46, 38, 13, 77],\n        [74, 19, 58, 95, 51]],\n\n       [[60, 60, 14, 98, 86],\n        [14, 37,  7, 92, 26],\n        [29, 83, 67, 54, 33]]]) '

In [22]:
a = np.random.random_sample((2,3))
a

'''# Output: 
array([[0.98394726, 0.10662489, 0.48572397],
       [0.09429398, 0.93624063, 0.18387535]])'''

'# Output: \narray([[0.98394726, 0.10662489, 0.48572397],\n       [0.09429398, 0.93624063, 0.18387535]])'

In [23]:
type(a) # Output: numpy.ndarray
print(a.ndim) # Output: 2 
# nuestro array tiene 2 filas y 3 columnas
print(a.shape) # Output: (2,3)
# los datos que tenemos en nuestro array son de tipo float
print(a.dtype) # Output: dtypes('float64')


2
(2, 3)
float64


In [24]:
# Indexación en arrays
lst = [12,20,3,45,6,23,81,93]
# Seleccionamos desde el elemento 3 (incluido) hasta el final
print(lst[3:])  # Output: [45, 6, 23, 81, 93]

# Seleccionamos desde el elemento 3 hasta el 5. 
# ⚠️ El límite superior del valor que especificamos NO SE INCLUYE.

print(lst[3:6]) # Output: [45, 6, 23]

# Seleccionamos los 4 primeros elementos
lst[:4] # Output: [12, 20, 3, 45]

# Seleccionamos todos los elementos que están en posición impar
print(lst[::2]) # Output: [12, 3, 6, 81]

[45, 6, 23, 81, 93]
[45, 6, 23]
[12, 3, 6, 81]


In [25]:
unidimensional = np.random.random_sample(15)
print(unidimensional)

# Output: 
'''array([0.11004851, 0.04858927, 0.25918084, 0.98074997, 0.47281141,
       0.06919704, 0.73482103, 0.67461802, 0.9731047 , 0.61204223,
       0.64327416, 0.89920378, 0.25789705, 0.15254418, 0.64145759]) '''

[2.02062281e-01 8.53125573e-01 2.39227740e-01 4.17280916e-01
 6.97367877e-01 3.45798936e-01 7.10525452e-01 1.63537835e-01
 1.58651027e-01 7.80373431e-01 6.06507368e-01 5.87570010e-01
 4.66505118e-01 1.49144240e-04 3.63527176e-01]


'array([0.11004851, 0.04858927, 0.25918084, 0.98074997, 0.47281141,\n       0.06919704, 0.73482103, 0.67461802, 0.9731047 , 0.61204223,\n       0.64327416, 0.89920378, 0.25789705, 0.15254418, 0.64145759]) '

In [26]:
#Si queremos acceder al primer elemento de nuestro array
print(unidimensional[0]) # Output: 0.11004850610895134

#Si queremos acceder a los tres últimos elementos
print(unidimensional[-3:]) # Output: array([0.25789705, 0.15254418, 0.64145759])

#Si queremos acceder a los tres últimos elementos
print(unidimensional[-3:]) # Output: array([0.25789705, 0.15254418, 0.64145759])

# Si queremos seleccionar el tercer y cuarto elemento
print(unidimensional[3:5]) # Output: array([0.98074997, 0.47281141])

# Los elementos desde el inicio hasta el 10 en saltos de dos en dos
print(unidimensional[:11:2]) # Output: array([0.11004851, 0.25918084, 0.47281141, 0.73482103, 0.9731047 , 0.64327416])

0.2020622808618937
[4.66505118e-01 1.49144240e-04 3.63527176e-01]
[4.66505118e-01 1.49144240e-04 3.63527176e-01]
[0.41728092 0.69736788]
[0.20206228 0.23922774 0.69736788 0.71052545 0.15865103 0.60650737]


# arrays bidimensionales

In [27]:
bidimensional = np.random.rand(5, 4)
print(bidimensional)

[[0.07167624 0.36872102 0.75276074 0.77098189]
 [0.24390338 0.91918578 0.18968107 0.96944563]
 [0.37227248 0.04744971 0.01519299 0.0500616 ]
 [0.18272168 0.8981367  0.38858409 0.25594252]
 [0.61256322 0.55437218 0.44996947 0.46286765]]


In [28]:
# Accedemos a la fila 0
print(bidimensional[0]) # Output: array([0.63019968, 0.1409182 , 0.930998  , 0.88841414])

# Accedemos al elemento de la fila 0 columna 0
print(bidimensional[0,0]) # Output:  0.6301996771602075

# Esto es lo mismo que lo anterior
print(bidimensional[0][0]) # Output: 0.6301996771602075

# Segunda fila, tercer columna.
print(bidimensional[2,3]) # Output: 0.6651123761198269


[0.07167624 0.36872102 0.75276074 0.77098189]
0.07167624362217173
0.07167624362217173
0.050061601518093024


In [29]:
# Seleccionar las dos primeras filas,y todas las columnas (no ponemos nada después de la coma).
bidimensional[:2,:] # Output: array([[0.63019968, 0.1409182 , 0.930998  , 0.88841414],[0.01226318, 0.19209121, 0.86734263, 0.07889421]])


array([[0.07167624, 0.36872102, 0.75276074, 0.77098189],
       [0.24390338, 0.91918578, 0.18968107, 0.96944563]])

In [30]:
for columnas in range(bidimensional.shape[0]):
    for filas in range(bidimensional.shape[1]):
        if bidimensional[columnas,filas] > 0.5:
            bidimensional[columnas,filas] = -1

print(bidimensional)

[[ 0.07167624  0.36872102 -1.         -1.        ]
 [ 0.24390338 -1.          0.18968107 -1.        ]
 [ 0.37227248  0.04744971  0.01519299  0.0500616 ]
 [ 0.18272168 -1.          0.38858409  0.25594252]
 [-1.         -1.          0.44996947  0.46286765]]


In [31]:
print(bidimensional)
print(bidimensional[0,1])
print(bidimensional[1,0])

[[ 0.07167624  0.36872102 -1.         -1.        ]
 [ 0.24390338 -1.          0.18968107 -1.        ]
 [ 0.37227248  0.04744971  0.01519299  0.0500616 ]
 [ 0.18272168 -1.          0.38858409  0.25594252]
 [-1.         -1.          0.44996947  0.46286765]]
0.3687210169532775
0.24390337963447883


# arrays Multidimensional

In [32]:
multidimensional = np.random.randint(0,100, (2,3,5))
print(multidimensional)

[[[87 96 34 60  3]
  [37 57 75 85 35]
  [ 9 34 42 88 15]]

 [[12 15 35 16  0]
  [20 35 20 88 92]
  [73 12 96  5 32]]]


In [33]:
# Accedemos al array 1 y al elemento que está en la fila 2 y la columna 4
print(multidimensional[1,2,4]) # Output: 82

# Primer array primera fila y todas las columnas
print(multidimensional[0, 1, :]) # Output: array([75,  8, 57, 70, 70])

# En caso de que queramos que nos devuelva todas las filas
print(multidimensional[0][:][0]) # Output: array([68,  5, 12, 46, 99])


32
[37 57 75 85 35]
[87 96 34 60  3]


In [34]:
multidim = np.random.randint(1,10,(3,3,3))

print(multidim)

[[[1 9 6]
  [2 9 5]
  [1 7 6]]

 [[5 5 2]
  [4 5 1]
  [2 9 7]]

 [[9 8 6]
  [1 3 7]
  [3 7 6]]]


In [35]:
print(multidim[0,1,2])

5


In [36]:
print(multidim[2,2,:])

[3 7 6]


In [37]:
print(multidim[[0],[0],[0]])

[1]


# Subsets con una condicion

In [38]:
multidimensional2 = np.random.randint(0,100, (2,3,5))
print(multidimensional2)



[[[32 31  3 75 46]
  [36 60 69 96 88]
  [13  8 43 76 85]]

 [[24 97 11 98 24]
  [37 79 72 76 63]
  [58 66 81  3 81]]]


In [39]:
print(multidimensional2 > 45)


[[[False False False  True  True]
  [False  True  True  True  True]
  [False False False  True  True]]

 [[False  True False  True False]
  [False  True  True  True  True]
  [ True  True  True False  True]]]


In [40]:
print(multidimensional2[multidimensional2 > 45])

[75 46 60 69 96 88 76 85 97 98 79 72 76 63 58 66 81 81]


In [41]:
multidimensional2[(multidimensional2 > 45 )  & (multidimensional2 == 77)]

# Output: array([62])

array([], dtype=int32)

In [42]:
multidimensional2[(multidimensional2 > 60 )  | (multidimensional2 < 15)]

array([ 3, 75, 69, 96, 88, 13,  8, 76, 85, 97, 11, 98, 79, 72, 76, 63, 66,
       81,  3, 81], dtype=int32)

# Operaciones array - escalar

In [43]:
c = np.array([[1,2,3], [3,4,5]])
c

array([[1, 2, 3],
       [3, 4, 5]])

In [44]:
print(c + 4)


print(c - 2)



[[5 6 7]
 [7 8 9]]
[[-1  0  1]
 [ 1  2  3]]


In [45]:
print(c * 2)
# Output: 
'''array([[ 2,  4,  6],
       [ 6,  8, 10]])'''

print(c / 3)
# Output: 
'''array([[0.33333333, 0.66666667, 1.        ],
       [1.        , 1.33333333, 1.66666667]])'''

[[ 2  4  6]
 [ 6  8 10]]
[[0.33333333 0.66666667 1.        ]
 [1.         1.33333333 1.66666667]]


'array([[0.33333333, 0.66666667, 1.        ],\n       [1.        , 1.33333333, 1.66666667]])'

In [46]:
print(c % 3)
# Output: 
'''array([[1, 2, 0],
       [0, 1, 2]])'''

print(c // 3)
# Output: 
'''array([[0, 0, 1],
       [1, 1, 1]])'''

print(c ** 3)
# Output: 
'''array([[  1,   8,  27],
       [ 27,  64, 125]])'''


[[1 2 0]
 [0 1 2]]
[[0 0 1]
 [1 1 1]]
[[  1   8  27]
 [ 27  64 125]]


'array([[  1,   8,  27],\n       [ 27,  64, 125]])'

# Operaciones entre arrays

In [47]:
a = np.ones((2,3,4))
b = np.random.randint(0,10, (2,3,4))

print(a)

print(b)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[[[8 7 4 1]
  [3 6 0 6]
  [7 8 1 3]]

 [[1 0 4 6]
  [7 9 6 5]
  [8 4 2 0]]]


In [48]:
# suma
print(a + b)

suma = np.add(a, b)
print(suma)

suma.astype(int)

[[[ 9.  8.  5.  2.]
  [ 4.  7.  1.  7.]
  [ 8.  9.  2.  4.]]

 [[ 2.  1.  5.  7.]
  [ 8. 10.  7.  6.]
  [ 9.  5.  3.  1.]]]
[[[ 9.  8.  5.  2.]
  [ 4.  7.  1.  7.]
  [ 8.  9.  2.  4.]]

 [[ 2.  1.  5.  7.]
  [ 8. 10.  7.  6.]
  [ 9.  5.  3.  1.]]]


array([[[ 9,  8,  5,  2],
        [ 4,  7,  1,  7],
        [ 8,  9,  2,  4]],

       [[ 2,  1,  5,  7],
        [ 8, 10,  7,  6],
        [ 9,  5,  3,  1]]])

In [49]:
# resta

print(b-a)

np.subtract(b,a)

[[[ 7.  6.  3.  0.]
  [ 2.  5. -1.  5.]
  [ 6.  7.  0.  2.]]

 [[ 0. -1.  3.  5.]
  [ 6.  8.  5.  4.]
  [ 7.  3.  1. -1.]]]


array([[[ 7.,  6.,  3.,  0.],
        [ 2.,  5., -1.,  5.],
        [ 6.,  7.,  0.,  2.]],

       [[ 0., -1.,  3.,  5.],
        [ 6.,  8.,  5.,  4.],
        [ 7.,  3.,  1., -1.]]])

In [50]:
# multiplicación

print(a * b)

np.multiply(a,b)

[[[8. 7. 4. 1.]
  [3. 6. 0. 6.]
  [7. 8. 1. 3.]]

 [[1. 0. 4. 6.]
  [7. 9. 6. 5.]
  [8. 4. 2. 0.]]]


array([[[8., 7., 4., 1.],
        [3., 6., 0., 6.],
        [7., 8., 1., 3.]],

       [[1., 0., 4., 6.],
        [7., 9., 6., 5.],
        [8., 4., 2., 0.]]])

In [51]:
# división

print(b/a)

np.divide(b,a)

[[[8. 7. 4. 1.]
  [3. 6. 0. 6.]
  [7. 8. 1. 3.]]

 [[1. 0. 4. 6.]
  [7. 9. 6. 5.]
  [8. 4. 2. 0.]]]


array([[[8., 7., 4., 1.],
        [3., 6., 0., 6.],
        [7., 8., 1., 3.]],

       [[1., 0., 4., 6.],
        [7., 9., 6., 5.],
        [8., 4., 2., 0.]]])

In [53]:
# División entera

y = b//a
print(y)



[[[8. 7. 4. 1.]
  [3. 6. 0. 6.]
  [7. 8. 1. 3.]]

 [[1. 0. 4. 6.]
  [7. 9. 6. 5.]
  [8. 4. 2. 0.]]]


# Operaciones estadísticas

In [54]:
d = np.random.randint(1,20, (4,5))
print(d)

[[13 14 15  5  5]
 [14 18 13 12  2]
 [ 8 16  4 10 11]
 [19 17  4  7  3]]


In [ ]:
# media
media = np.mean(d)
print(media)

10.5


In [ ]:
# media por filas
media_filas = np.mean(d, axis = 1)
media_filas

# Output: array([8.8, 9.6, 8.8, 9.8])

array([10.4, 11.8,  9.8, 10. ])

In [ ]:
# media por columnas
media_columnas = np.mean(d, axis = 0)
media_columnas

# Output: array([10.  ,  6.25, 12.5 ,  6.  , 11.5 ])

array([13.5 , 16.25,  9.  ,  8.5 ,  5.25])

In [ ]:
# Desviación estándar
np.std(d)

# Output: 5.92347026665957

np.float64(5.2583267300539625)

In [ ]:
# Desviación estándar por columnas
np.std(d, axis = 0)

# Output: array([4.94974747, 5.67340286, 4.38748219, 4.84767986, 6.34428877])


array([3.90512484, 1.47901995, 5.04975247, 2.6925824 , 3.49106001])

In [ ]:
# Desviación estándar por filas

np.std(d, axis = 1)

# Output: array([6.7349833 , 5.95315043, 5.97996656, 4.79165942])

array([4.45421149, 5.30659966, 3.91918359, 6.69328021])

In [ ]:
# variaza

np.var(d)
# Output: 35.0875

np.float64(27.65)

In [ ]:
# variaza por columnas

np.var(d, axis = 0)

# Output: array([24.5   , 32.1875, 19.25  , 23.5   , 40.25  ])

array([15.25  ,  2.1875, 25.5   ,  7.25  , 12.1875])

In [64]:
# variaza por filas

np.var(d, axis = 1)

# Output: array([45.36, 35.44, 35.76, 22.96])

array([19.84, 28.16, 15.36, 44.8 ])

# Operaciones aritméticas

In [84]:
d = np.random.randint(1,20, (4,5))

d

array([[ 4,  9,  6,  7, 10],
       [17, 11,  9,  9,  2],
       [ 7, 18,  6, 13,  4],
       [15, 18,  9, 19,  2]], dtype=int32)

In [85]:
# valor mínimo

np.min(d)

np.int32(2)

In [86]:
# valor mínimo por columnas

np.min(d, axis = 0)
# Output: array([4, 2, 8, 1, 1])

array([4, 9, 6, 7, 2], dtype=int32)

In [87]:
# valor mínimo por filas

np.min(d, axis = 1)
# Output: array([2, 1, 1, 3])

array([4, 2, 4, 2], dtype=int32)

In [69]:
# valor máximo
np.max(d)
# Output: 19

np.int32(19)

In [70]:
# valor máximo por columnas

np.max(d, axis = 0)

array([15, 13,  9, 17, 19], dtype=int32)

In [71]:
# valor máximo por filas

np.max(d, axis = 1)

array([19, 13, 17, 17], dtype=int32)

In [72]:
# suma

np.sum(d)

np.int64(208)

In [73]:
# suma por columna

np.sum(d,axis=0)


array([46, 42, 17, 58, 45])

In [75]:
# suma por fila

np.sum(d,axis=1)

array([70, 33, 65, 40])

In [76]:
# suma acumulada

np.cumsum(d)

array([ 12,  25,  34,  51,  70,  81,  94,  95, 102, 103, 118, 129, 135,
       152, 168, 176, 181, 182, 199, 208])

In [77]:
# suma acumulada por columnas

np.cumsum(d, axis = 0)

array([[12, 13,  9, 17, 19],
       [23, 26, 10, 24, 20],
       [38, 37, 16, 41, 36],
       [46, 42, 17, 58, 45]])

In [78]:
# suma acumulada por filas

np.cumsum(d, axis = 1)

array([[12, 25, 34, 51, 70],
       [11, 24, 25, 32, 33],
       [15, 26, 32, 49, 65],
       [ 8, 13, 14, 31, 40]])

In [79]:
# producto acumulado

np.cumprod(d)


array([                12,                156,               1404,
                    23868,             453492,            4988412,
                 64849356,           64849356,          453945492,
                453945492,         6809182380,        74901006180,
             449406037080,      7639902630360,    122238442085760,
          977907536686080,   4889537683430400,   4889537683430400,
        83122140618316800, 748099265564851200])

In [80]:
# raíz cuadrada

np.sqrt(d)


array([[3.46410162, 3.60555128, 3.        , 4.12310563, 4.35889894],
       [3.31662479, 3.60555128, 1.        , 2.64575131, 1.        ],
       [3.87298335, 3.31662479, 2.44948974, 4.12310563, 4.        ],
       [2.82842712, 2.23606798, 1.        , 4.12310563, 3.        ]])

In [81]:
# exponencial 

np.exp(d)

array([[1.62754791e+05, 4.42413392e+05, 8.10308393e+03, 2.41549528e+07,
        1.78482301e+08],
       [5.98741417e+04, 4.42413392e+05, 2.71828183e+00, 1.09663316e+03,
        2.71828183e+00],
       [3.26901737e+06, 5.98741417e+04, 4.03428793e+02, 2.41549528e+07,
        8.88611052e+06],
       [2.98095799e+03, 1.48413159e+02, 2.71828183e+00, 2.41549528e+07,
        8.10308393e+03]])

In [88]:
# Operaciones de comparación

d = np.random.randint(1,20, (4,5))
d

array([[13, 19, 10,  9, 12],
       [ 2, 18, 16, 15,  2],
       [ 7, 15, 10, 15, 16],
       [ 7, 15,  9, 12,  1]], dtype=int32)

In [94]:
print(np.any(d > 10))
# Output: True

print(np.any(d > 20))
# Output: False

print(np.any(d > 10, axis = 0))
# Output: array([ True,  True,  True,  True,  True])

print(np.any(d < 2 , axis = 1 ))
# Output: array([False,  True,  True, False])


True
False
[ True  True  True  True  True]
[False False False  True]


In [95]:
print(np.all(d > 10))
# Output: True

print(np.all(d > 20))
# Output: False

print(np.all(d > 10, axis = 0))
# Output: array([ True,  True,  True,  True,  True])

print(np.all(d < 2 , axis = 1 ))
# Output: array([False,  True,  True, False])

False
False
[False  True False False False]
[False False False False]


# Métodos de los arrays

In [96]:
nuevo_array = np.empty((3,4))
print(nuevo_array)

# Output: 
'''array([[1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.]])'''

nuevo_array_copia = nuevo_array.copy()
print(nuevo_array_copia)

# Output: 
'''array([[1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.]])'''


[[7.54381992e-312 2.47032823e-322 0.00000000e+000 0.00000000e+000]
 [1.57487907e-267 2.42336543e-057 6.50336913e-091 7.62484488e+169]
 [5.51073720e+169 2.62985891e-052 3.99910963e+252 8.06889583e+169]]
[[7.54381992e-312 2.47032823e-322 0.00000000e+000 0.00000000e+000]
 [1.57487907e-267 2.42336543e-057 6.50336913e-091 7.62484488e+169]
 [5.51073720e+169 2.62985891e-052 3.99910963e+252 8.06889583e+169]]


'array([[1., 0., 0., 0.],\n       [1., 0., 0., 0.],\n       [1., 0., 0., 0.]])'

In [97]:
nuevo_array_copia[0,0] = 20
nuevo_array_copia

array([[2.00000000e+001, 2.47032823e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.57487907e-267, 2.42336543e-057, 6.50336913e-091,
        7.62484488e+169],
       [5.51073720e+169, 2.62985891e-052, 3.99910963e+252,
        8.06889583e+169]])

In [98]:

h = np.arange(1,20)
print(h)

# Output: array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,18, 19])

np.transpose(h)
# Output: array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,18, 19])



[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [99]:
# nos creamos un array

bidimensional = np.random.rand(5, 4)
print(bidimensional)

np.transpose(bidimensional)

[[0.72490493 0.3779407  0.96390641 0.23422257]
 [0.70886236 0.03404481 0.90404071 0.14882859]
 [0.35233778 0.8319715  0.54308764 0.14920366]
 [0.50360747 0.22144103 0.30339091 0.1955304 ]
 [0.82775721 0.02666745 0.16752719 0.39765031]]


array([[0.72490493, 0.70886236, 0.35233778, 0.50360747, 0.82775721],
       [0.3779407 , 0.03404481, 0.8319715 , 0.22144103, 0.02666745],
       [0.96390641, 0.90404071, 0.54308764, 0.30339091, 0.16752719],
       [0.23422257, 0.14882859, 0.14920366, 0.1955304 , 0.39765031]])

In [101]:
# nos creamos un array
multidimensional = np.random.randint(0,100, (2,3,5))
print(multidimensional)

np.transpose(multidimensional)


[[[28  3 90 22 70]
  [51 75  1  8 28]
  [50 92 61 94 16]]

 [[38 24 90 98  4]
  [13 12 65 64 52]
  [76 38 60 65 14]]]


array([[[28, 38],
        [51, 13],
        [50, 76]],

       [[ 3, 24],
        [75, 12],
        [92, 38]],

       [[90, 90],
        [ 1, 65],
        [61, 60]],

       [[22, 98],
        [ 8, 64],
        [94, 65]],

       [[70,  4],
        [28, 52],
        [16, 14]]], dtype=int32)

In [102]:
np.transpose(multidimensional, (1,2,0))

array([[[28, 38],
        [ 3, 24],
        [90, 90],
        [22, 98],
        [70,  4]],

       [[51, 13],
        [75, 12],
        [ 1, 65],
        [ 8, 64],
        [28, 52]],

       [[50, 76],
        [92, 38],
        [61, 60],
        [94, 65],
        [16, 14]]], dtype=int32)

In [103]:

array2

# Output: 
'''array([[1, 2, 3],
       [4, 5, 6]])'''

array2.reshape(3,2)

# Output: 
'''array([[1, 2],
       [3, 4],
       [5, 6]])'''


'array([[1, 2],\n       [3, 4],\n       [5, 6]])'

In [104]:
forma = np.arange(12)
print(forma)

# Output: array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

forma.reshape(2,3,2)

# Output: 
'''array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])'''


[ 0  1  2  3  4  5  6  7  8  9 10 11]


'array([[[ 0,  1],\n        [ 2,  3],\n        [ 4,  5]],\n\n       [[ 6,  7],\n        [ 8,  9],\n        [10, 11]]])'

In [105]:

array2

# Output: 
'''array([[1, 2, 3],
       [4, 5, 6]])'''

# nos ha convertido las filas en columnas y viceversa
np.swapaxes(array2,1,0)

# Output: 
'''array([[1, 4],
       [2, 5],
       [3, 6]])'''


'array([[1, 4],\n       [2, 5],\n       [3, 6]])'

# Funciones de vectores

In [106]:

vector1 = np.random.randint(3, 15, 7)
print(vector1)
# Output: array([ 9,  5, 10, 14, 11,  6, 11])


vector2 = np.random.randint(0,10, 7)
print(vector2)
# Output: array([4, 6, 0, 3, 8, 8, 5])



[11 11  5 10  3 10  7]
[3 3 3 5 5 9 9]


In [108]:
# creemos un nuevo array 

arr3 = np.random.randint(1,10, (4,5))
print(arr3)

# creemos un nuevo array 

np.unique(arr3)

# Output: array([1, 3, 4, 5, 6, 8, 9])

np.unique(arr3, return_index = True)

# Output: (array([1, 3, 4, 5, 6, 8, 9]), array([ 1,  4,  5, 11,  2,  3,  0]))






[[3 3 7 9 4]
 [5 6 6 4 3]
 [3 1 5 9 1]
 [4 9 3 8 4]]


(array([1, 3, 4, 5, 6, 7, 8, 9], dtype=int32),
 array([11,  0,  4,  5,  6,  2, 18,  3]))

In [109]:
# definimos dos arrays
arr1 = np.array([4,5,6,8])
arr2 = np.array([4,9,1,5])

print(arr1)
# Output array([4, 5, 6, 8])
print(arr2)
# Output array([4, 9, 1, 5])


# aplicamos el método np.intersect1d y nos devuelve los elementos que están en los dos arrays
np.intersect1d(arr1, arr2)
# Output array([4, 5])


[4 5 6 8]
[4 9 1 5]


array([4, 5])

In [110]:
# definimos dos arrays
arr1 = np.array([4,5,6,8])
arr2 = np.array([4,9,1,5])

print(arr1)
# Output array([4, 5, 6, 8])
print(arr2)
# Output array([4, 9, 1, 5])

# aplicamos el método con el parámetro return_indices
np.intersect1d(arr1, arr2, return_indices=True)
# Output (array([4, 5]), array([0, 1]), array([0, 3]))




[4 5 6 8]
[4 9 1 5]


(array([4, 5]), array([0, 1]), array([0, 3]))

In [111]:
# definimos dos arrays
arr1 = np.array([4,5,6,8])
arr2 = np.array([4,9,1,5])

print(arr1)
# Output array([4, 5, 6, 8])


print(arr2)
# Output array([4, 9, 1, 5])


# Aplicamos el método 
np.union1d(arr1, arr2)

# Output array([1, 4, 5, 6, 8, 9])


[4 5 6 8]
[4 9 1 5]


array([1, 4, 5, 6, 8, 9])

In [121]:
# definimos dos arrays
arr1 = np.array([4,5,6,8])
arr2 = np.array([4,9,1,5])

print(arr1)
# Output array([4, 5, 6, 8])


print(arr2)
# Output array([4, 9, 1, 5])

# aplicamos el método
np.in1d(arr2, arr1)
#np.intersect1d(arr1, arr2)
# Output array([ True,  True, False, False])

[4 5 6 8]
[4 9 1 5]


AttributeError: module 'numpy' has no attribute 'in1d'

In [115]:
# definimos dos arrays
arr1 = np.array([4,5,6,8])
arr2 = np.array([4,9,1,5])

print(arr1)
# Output array([4, 5, 6, 8])
print(arr2)
# Output array([4, 9, 1, 5])


# aplicamos el método
np.setdiff1d(arr1, arr2)
# Output array([6, 8])
# los valores de 6 y 8 los encontramos en el arr1, pero no en el arr2





[4 5 6 8]
[4 9 1 5]


array([6, 8])

In [116]:
# definimos dos arrays
arr1 = np.array([4,5,6,8])
arr2 = np.array([4,9,1,5])

print(arr1)
# Output array([4, 5, 6, 8])


print(arr2)
# Output array([4, 9, 1, 5])


# Aplicamos el método
np.setdiff1d(arr2, arr1)

# Output array([1, 9])
# los valores 1, 9 están en el arr2, pero no en el arr1


[4 5 6 8]
[4 9 1 5]


array([1, 9])

In [3]:
# definimos dos arrays
arr1 = np.array([4,5,6,8])
arr2 = np.array([4,9,1,5])

print(arr1)
# Output array([4, 5, 6, 8])


print(arr2)
# Output array([4, 9, 1, 5])


# Aplicamos el método
np.setxor1d(arr1, arr2)

# Output array([1, 6, 8, 9])
# los números 1,6,8,9 van a estar únicamente en un array. El 
# 6 y 8 están solo en el arr1 y el 1 y 9 solo en el arr2




[4 5 6 8]
[4 9 1 5]


array([1, 6, 8, 9])